config_version: "0.2"

schema_list:
  - schema: biline_pinyin

menu:
  page_size: 25

switcher:
  hotkeys: []

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
